/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShiftClosingDialog: typeof import('./src/components/ShiftClosingDialog.vue')['default']
    ShiftOpeningDialog: typeof import('./src/components/ShiftOpeningDialog.vue')['default']
  }
}
